### ISSUE TITLE
Only raise runtime exception if --exec is passed

### ISSUE THREAD

**Issue by sionsmith** [ashleygould/aws-orgs#6]
Currently when you run:

organization -v -s samples/org-spec.yaml 

If the policy is not created then you a RuntimeError is thrown, this should only happen if the --exec flag is passed.

See full stack below:
/usr/local/bin/python2.7 /Users/sionsmith/development/oso/aws-orgs/awsorgs/orgs.py organization -v -s samples/org-spec.yaml
[dryrun] awsorgs.utils: INFO     Updating policy 'infrastructure_service_policy'
[dryrun] awsorgs.utils: INFO     Updating policy 'logging_service_policy'
[dryrun] awsorgs.utils: INFO     Creating policy 'aduit_only_policy'
[dryrun] awsorgs.utils: INFO     Creating policy 'iam_only_policy'
[dryrun] awsorgs.utils: INFO     Creating policy 'application_account_policy'
[dryrun] awsorgs.utils: WARNING  Account 'global_services' not yet in Organization
[dryrun] awsorgs.utils: WARNING  Account 'service_catalogue' not yet in Organization
[dryrun] awsorgs.utils: WARNING  Account 'management' not yet in Organization
[dryrun] awsorgs.utils: WARNING  Account 'iam_master' not yet in Organization
[dryrun] awsorgs.utils: WARNING  Account 'logging' not yet in Organization
Traceback (most recent call last):
  File "/Users/sionsmith/development/oso/aws-orgs/awsorgs/orgs.py", line 449, in <module>
    main()
  File "/Users/sionsmith/development/oso/aws-orgs/awsorgs/orgs.py", line 436, in main
    org_spec['organizational_units'], 'root')
  File "/Users/sionsmith/development/oso/aws-orgs/awsorgs/orgs.py", line 360, in manage_ou
    ou_spec['Child_OU'], ou_spec['Name'])
  File "/Users/sionsmith/development/oso/aws-orgs/awsorgs/orgs.py", line 379, in manage_ou
    deployed, org_spec, ou_spec, ou['Id'])
  File "/Users/sionsmith/development/oso/aws-orgs/awsorgs/orgs.py", line 332, in manage_policy_attachments
    policy_name)
RuntimeError: spec-file: ou_spec: policy 'aduit_only_policy' not defined

Process finished with exit code 1

**Comment by ashleygould** [comment]
Thanks, agian. Will you work on it or shall I?

**Comment by sionsmith** [comment]
I've pushed a simple fix and created a pull request on the repo :)
